import type { Interval, IntervalKey } from '../types'

export const INTERVALS: Record<IntervalKey, Interval> = {
  P1: { symbol: 'P1', pitch_step: 0, letter_step: 0, name: 'Perfect Unison' },
  A1: { symbol: 'A1', pitch_step: 1, letter_step: 0, name: 'Augmented Unison' },
  m2: { symbol: 'm2', pitch_step: 1, letter_step: 1, name: 'Minor Second' },
  M2: { symbol: 'M2', pitch_step: 2, letter_step: 1, name: 'Major Second' },
  A2: { symbol: 'A2', pitch_step: 3, letter_step: 1, name: 'Augmented Second' },
  m3: { symbol: 'm3', pitch_step: 3, letter_step: 2, name: 'Minor Third' },
  M3: { symbol: 'M3', pitch_step: 4, letter_step: 2, name: 'Major Third' },
  P4: { symbol: 'P4', pitch_step: 5, letter_step: 3, name: 'Perfect Fourth' },
  A4: { symbol: 'A4', pitch_step: 6, letter_step: 3, name: 'Augmented Fourth' },
  d5: { symbol: 'd5', pitch_step: 6, letter_step: 4, name: 'Diminished Fifth' },
  P5: { symbol: 'P5', pitch_step: 7, letter_step: 4, name: 'Perfect Fifth' },
  A5: { symbol: 'A5', pitch_step: 8, letter_step: 4, name: 'Augmented Fifth' },
  m6: { symbol: 'm6', pitch_step: 8, letter_step: 5, name: 'Minor Sixth' },
  M6: { symbol: 'M6', pitch_step: 9, letter_step: 5, name: 'Major Sixth' },
  d7: { symbol: 'd7', pitch_step: 9, letter_step: 6, name: 'Diminished Seventh' },
  m7: { symbol: 'm7', pitch_step: 10, letter_step: 6, name: 'Minor Seventh' },
  M7: { symbol: 'M7', pitch_step: 11, letter_step: 6, name: 'Major Seventh' },
  P8: { symbol: 'P8', pitch_step: 12, letter_step: 7, name: 'Perfect Octave' },
  M9: { symbol: 'M9', pitch_step: 14, letter_step: 8, name: 'Major Ninth' },
  m9: { symbol: 'm9', pitch_step: 13, letter_step: 8, name: 'Minor Ninth' },
  A9: { symbol: 'A9', pitch_step: 15, letter_step: 8, name: 'Augmented Ninth' },
  M11: { symbol: 'M11', pitch_step: 17, letter_step: 10, name: 'Major Eleventh' },
  m11: { symbol: 'm11', pitch_step: 16, letter_step: 10, name: 'Minor Eleventh' },
  P11: { symbol: 'P11', pitch_step: 17, letter_step: 10, name: 'Perfect Eleventh' },
  A11: { symbol: 'A11', pitch_step: 18, letter_step: 10, name: 'Augmented Eleventh' },
  M13: { symbol: 'M13', pitch_step: 21, letter_step: 12, name: 'Major Thirteenth' },
  m13: { symbol: 'm13', pitch_step: 20, letter_step: 12, name: 'Minor Thirteenth' },
  A13: { symbol: 'A13', pitch_step: 22, letter_step: 12, name: 'Augmented Thirteenth' },
} as const
