import type { Interval, Scale } from '../types'
import { INTERVALS } from './intervals'

export const SCALES: Record<Scale, Interval[]> = {
  // --- DIATONIC MODES ---
  MAJOR: [INTERVALS.M2, INTERVALS.M3, INTERVALS.P4, INTERVALS.P5, INTERVALS.M6, INTERVALS.M7],
  MINOR: [INTERVALS.M2, INTERVALS.m3, INTERVALS.P4, INTERVALS.P5, INTERVALS.m6, INTERVALS.m7],
  IONIAN: [INTERVALS.M2, INTERVALS.M3, INTERVALS.P4, INTERVALS.P5, INTERVALS.M6, INTERVALS.M7],
  DORIAN: [INTERVALS.M2, INTERVALS.m3, INTERVALS.P4, INTERVALS.P5, INTERVALS.M6, INTERVALS.m7],
  PHRYGIAN: [INTERVALS.m2, INTERVALS.m3, INTERVALS.P4, INTERVALS.P5, INTERVALS.m6, INTERVALS.m7],
  LYDIAN: [INTERVALS.M2, INTERVALS.M3, INTERVALS.A4, INTERVALS.P5, INTERVALS.M6, INTERVALS.M7],
  MIXOLYDIAN: [INTERVALS.M2, INTERVALS.M3, INTERVALS.P4, INTERVALS.P5, INTERVALS.M6, INTERVALS.m7],
  LOCRIAN: [INTERVALS.m2, INTERVALS.m3, INTERVALS.P4, INTERVALS.d5, INTERVALS.m6, INTERVALS.m7],

  // --- MINOR VARIANTS ---
  HARMONIC_MINOR: [
    INTERVALS.M2,
    INTERVALS.m3,
    INTERVALS.P4,
    INTERVALS.P5,
    INTERVALS.m6,
    INTERVALS.M7,
  ],
  MELODIC_MINOR: [
    INTERVALS.M2,
    INTERVALS.m3,
    INTERVALS.P4,
    INTERVALS.P5,
    INTERVALS.M6,
    INTERVALS.M7,
  ],

  // --- PENTATONIC & BLUES ---
  MAJOR_PENTATONIC: [INTERVALS.M2, INTERVALS.M3, INTERVALS.P5, INTERVALS.M6],
  MINOR_PENTATONIC: [INTERVALS.m3, INTERVALS.P4, INTERVALS.P5, INTERVALS.m7],
  BLUES: [INTERVALS.m3, INTERVALS.P4, INTERVALS.d5, INTERVALS.P5, INTERVALS.m7],

  // --- SYMMETRICAL & EXOTIC ---
  WHOLE_TONE: [INTERVALS.M2, INTERVALS.M3, INTERVALS.A4, INTERVALS.A5, INTERVALS.m7],
  CHROMATIC: [
    INTERVALS.A1,
    INTERVALS.M2,
    INTERVALS.m3,
    INTERVALS.M3,
    INTERVALS.P4,
    INTERVALS.A4,
    INTERVALS.P5,
    INTERVALS.m6,
    INTERVALS.M6,
    INTERVALS.m7,
    INTERVALS.M7,
  ],
} as const
